// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FormatDistanceToNow from "date-fns/formatDistanceToNow";

console.log(FormatDistanceToNow(new Date()));

export {
  
}
/*  Not a pure module */
