// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var FormatDistanceToNow = require("date-fns/formatDistanceToNow");

console.log(FormatDistanceToNow(new Date()));

/*  Not a pure module */
